name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  deploy-on-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.13.1
        with:
          minikube_version: 'v1.35.0'
          kubernetes_version: 'v1.32.0'

      - name: Install kubectl (optional)
        # Use this step if not downloading kubectl from a previous workflow run
        run: |
          sudo apt update && sudo apt-get install -y kubectl
      - name: Apply Kubernetes resources
        run: |
          kubectl apply -f portfolio.yaml
          kubectl apply -f portfolioservice.yaml
      - name: Wait for deployment
        run: sleep 30s

      - name: Verify deployment status
        run: |
          echo "--- Pods"
          kubectl get pods
          echo "--- Deployments"
          kubectl get deployments
          echo "--- Services"
          kubectl get services
          minikube service --all
          minikube logs