# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

    
jobs:
    deploy-on-push:
        runs-on : ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            - name: Setup Minikube
              uses: manusa/actions-setup-minikube@v2.13.1
              with:
                minikube version: 'v1.35.0'
                kubernetes version: 'v1.32.0'
            
            - name: minikube start
              run: |
                minikube start 
                minikube status 

            - name: install chrome
              run: |
                sudo apt install snapd
                sudo snap install k9s --devmode 


            - name: apply k8s portfolio.yaml
            
              run: |
                kubectl apply -f portfolio.yaml
                kubectl get pods

                
                
            - name: Sleep for 180 seconds
              uses: jakejarvis/wait-action@master
              with:
                time: '100s'

                
            - name: check deployment 
              run: |
                kubectl apply -f portfolioservice.yaml
                echo "---------------------Pods"
                kubectl get pods
                echo "---------------------deployments"
                kubectl get deployment
                echo "Pods"
                kubectl get service 
                echo "--------------------Services"
                minikube service --all --url
                minikube logs

