# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

    
jobs:
    deploy-on-push:
        runs-on : self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            
            # - name: Setup Minikube
            #   uses: manusa/actions-setup-minikube@v2.13.1
            #   options: --user root
            #   with:
            #     minikube version: 'v1.35.0'
            #     kubernetes version: 'v1.32.0'

            - name: install kctl
              run: |
                sudo apt-get update
                snap install kubectl --classic
                kubectl version --client

            
            
            - name: minikube start
              run: |
                curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
                sudo dpkg -i minikube_latest_amd64.deb
                minikube start 
                minikube status 

            # - name: install chrome
            #   run: |
            #     sudo apt install snapd
            #     sudo snap install k9s --devmode 


            - name: apply k8s portfolio.yaml
            
              run: |
                kubectl apply -f portfolio.yaml
                kubectl apply -f portfolioservice.yaml
                

                
                
            - name: Sleep for 30 seconds
              run: sleep 30s
              shell: bash

                
            - name: check deployment 
              run: |

                echo "---------------------Pods"
                kubectl get pods
                echo "---------------------deployments"
                kubectl get deployment
                echo "Pods"
                kubectl get service 
                echo "--------------------Services"
                minikube service --all 
                minikube logs

